config/routes.rb
Rails.application.routes.draw do
  
  namespace :cms_admin, :path => ComfortableMexicanSofa.config.admin_route_prefix, :except => :show do
    get '/' => redirect(
      "/#{ComfortableMexicanSofa.config.admin_route_prefix}/#{ComfortableMexicanSofa.config.admin_route_redirect}"
    )
    resources :pages do
      member do 
        match :form_blocks
        match :toggle_branch
      end
      collection do
        match :reorder
      end
      resources :revisions, :only => [:index, :show, :revert] do
        put :revert, :on => :member
      end
    end
    resources :sites
    resources :uploads, :only => [:create, :destroy]
    resources :layouts do
      resources :revisions, :only => [:index, :show, :revert] do
        put :revert, :on => :member
      end
    end
    resources :snippets do 
      resources :revisions, :only => [:index, :show, :revert] do
        put :revert, :on => :member
      end
    end
  end unless ComfortableMexicanSofa.config.admin_route_prefix.blank?
  
  scope :controller => :cms_content do
    prefix = ComfortableMexicanSofa.config.content_route_prefix
    get "#{prefix}/cms-css/:id"  => :render_css,   :as => 'cms_css'
    get "#{prefix}/cms-js/:id"   => :render_js,    :as => 'cms_js'
    get "#{prefix}/"             => :render_html,  :as => 'cms_html',  :path => "#{prefix}/(*cms_path)"
  end
  
end

app/controllers/cms_admin/base_controller.rb
class CmsAdmin::BaseController < ApplicationController
  
  protect_from_forgery
  
  # Authentication module must have #authenticate method
  include ComfortableMexicanSofa.config.authentication.to_s.constantize
  
  before_filter :authenticate,
                :load_admin_cms_site
  
  layout 'cms_admin'
  
protected
  
  def load_admin_cms_site
    hostname = request.host.downcase
    @cms_site = Cms::Site.find_by_hostname!(hostname)
    
  rescue ActiveRecord::RecordNotFound
    unless ComfortableMexicanSofa.config.enable_multiple_sites
      if Cms::Site.count == 0
        @cms_site = Cms::Site.create!(:label => 'Default Site', :hostname => hostname)
      else
        @cms_site = Cms::Site.first
        @cms_site.update_attribute(:hostname, hostname)
      end
    end
    
    unless @cms_site
      flash[:error] = 'No Site defined for this hostname. Create it now.'
      return redirect_to(cms_admin_sites_path)
    end
  end
end

app/controllers/cms_admin/layouts_controller.rb
class CmsAdmin::LayoutsController < CmsAdmin::BaseController

  before_filter :build_cms_layout,  :only => [:new, :create]
  before_filter :load_cms_layout,   :only => [:edit, :update, :destroy]

  def index
    return redirect_to :action => :new if @cms_site.layouts.count == 0
    @cms_layouts = @cms_site.layouts.roots
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @cms_layout.save!
    flash[:notice] = 'Layout created'
    redirect_to :action => :edit, :id => @cms_layout
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create layout'
    render :action => :new
  end

  def update
    @cms_layout.update_attributes!(params[:cms_layout])
    flash[:notice] = 'Layout updated'
    redirect_to :action => :edit, :id => @cms_layout
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update layout'
    render :action => :edit
  end

  def destroy
    @cms_layout.destroy
    flash[:notice] = 'Layout deleted'
    redirect_to :action => :index
  end

protected

  def build_cms_layout
    @cms_layout = @cms_site.layouts.new(params[:cms_layout])
    @cms_layout.parent ||= Cms::Layout.find_by_id(params[:parent_id])
    @cms_layout.content ||= '{{ cms:page:content:text }}'
  end

  def load_cms_layout
    @cms_layout = @cms_site.layouts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Layout not found'
    redirect_to :action => :index
  end

end

app/controllers/cms_admin/pages_controller.rb
class CmsAdmin::PagesController < CmsAdmin::BaseController

  before_filter :check_for_layouts, :only => [:new, :edit]
  before_filter :build_cms_page,    :only => [:new, :create]
  before_filter :load_cms_page,     :only => [:edit, :update, :destroy]
  before_filter :preview_cms_page,  :only => [:create, :update]
  before_filter :build_upload_file, :only => [:new, :edit]

  def index
    return redirect_to :action => :new if @cms_site.pages.count == 0
    @cms_pages = [@cms_site.pages.root].compact
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @cms_page.save!
    flash[:notice] = 'Page saved'
    redirect_to :action => :edit, :id => @cms_page
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create page'
    render :action => :new
  end

  def update
    @cms_page.save!
    flash[:notice] = 'Page updated'
    redirect_to :action => :edit, :id => @cms_page
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update page'
    render :action => :edit
  end

  def destroy
    @cms_page.destroy
    flash[:notice] = 'Page deleted'
    redirect_to :action => :index
  end

  def form_blocks
    @cms_page = @cms_site.pages.find_by_id(params[:id]) || @cms_site.pages.new
    @cms_page.layout = @cms_site.layouts.find_by_id(params[:layout_id])
  end

  def toggle_branch
    @cms_page = @cms_site.pages.find(params[:id])
    s   = (session[:cms_page_tree] ||= [])
    id  = @cms_page.id.to_s
    s.member?(id) ? s.delete(id) : s << id
  rescue ActiveRecord::RecordNotFound
    # do nothing
  end

  def reorder
    (params[:cms_page] || []).each_with_index do |id, index|
      if (cms_page = Cms::Page.find_by_id(id))
        cms_page.update_attribute(:position, index)
      end
    end
    render :nothing => true
  end

protected

  def check_for_layouts
    if @cms_site.layouts.count == 0
      flash[:error] = 'No Layouts found. Please create one.'
      redirect_to new_cms_admin_layout_path
    end
  end

  def build_cms_page
    @cms_page = @cms_site.pages.new(params[:cms_page])
    @cms_page.parent ||= (@cms_site.pages.find_by_id(params[:parent_id]) || @cms_site.pages.root)
    @cms_page.layout ||= (@cms_page.parent && @cms_page.parent.layout || @cms_site.layouts.first)
  end

  def build_upload_file
    @upload = Cms::Upload.new
  end

  def load_cms_page
    @cms_page = @cms_site.pages.find(params[:id])
    @cms_page.attributes = params[:cms_page]
    @cms_page.layout ||= (@cms_page.parent && @cms_page.parent.layout || @cms_site.layouts.first)
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Page not found'
    redirect_to :action => :index
  end

  def preview_cms_page
    if params[:preview]
      layout = @cms_page.layout.app_layout.blank?? false : @cms_page.layout.app_layout
      render :inline => @cms_page.content(true), :layout => layout
    end
  end
end

app/controllers/cms_admin/revisions_controller.rb
class CmsAdmin::RevisionsController < CmsAdmin::BaseController
  
  before_filter :load_record
  before_filter :load_revision, :except => :index
  
  def index
    redirect_to :action => :show, :id => @record.revisions.first.try(:id) || 0
  end
  
  def show
    case @record
    when Cms::Page
      @current_content    = @record.blocks.inject({}){|c, b| c[b.label] = b.content; c }
      @versioned_content  = @record.blocks.inject({}){|c, b| c[b.label] = @revision.data['blocks_attributes'].detect{|r| r[:label] == b.label}.try(:[], :content); c }
    else
      @current_content    = @record.revision_fields.inject({}){|c, f| c[f] = @record.send(f); c }
      @versioned_content  = @record.revision_fields.inject({}){|c, f| c[f] = @revision.data[f]; c }
    end
  end
  
  def revert
    @record.restore_from_revision(@revision)
    flash[:notice] = 'Content Reverted'
    redirect_to_record
  end
  
protected
  
  def load_record
    @record = if params[:layout_id]
      Cms::Layout.find(params[:layout_id])
    elsif params[:page_id]
      Cms::Page.find(params[:page_id])
    elsif params[:snippet_id]
      Cms::Snippet.find(params[:snippet_id])
    end
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Record Not Found'
    redirect_to cms_admin_path
  end
  
  def load_revision
    @revision = @record.revisions.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Revision Not Found'
    redirect_to_record
  end
  
  def redirect_to_record
    redirect_to case @record
      when Cms::Layout  then edit_cms_admin_layout_path(@record)
      when Cms::Page    then edit_cms_admin_page_path(@record)
      when Cms::Snippet then edit_cms_admin_snippet_path(@record)
    end
  end
  
end

app/controllers/cms_admin/sites_controller.rb
class CmsAdmin::SitesController < CmsAdmin::BaseController

  skip_before_filter :load_admin_cms_site

  before_filter :build_cms_site,  :only => [:new, :create]
  before_filter :load_cms_site,   :only => [:edit, :update, :destroy]

  def index
    return redirect_to :action => :new if Cms::Site.count == 0
    @cms_sites = Cms::Site.all
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @cms_site.save!
    flash[:notice] = 'Site created'
    redirect_to :action => :edit, :id => @cms_site
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create site'
    render :action => :new
  end

  def update
    @cms_site.update_attributes!(params[:cms_site])
    flash[:notice] = 'Site updated'
    redirect_to :action => :edit, :id => @cms_site
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update site'
    render :action => :edit
  end

  def destroy
    @cms_site.destroy
    flash[:notice] = 'Site deleted'
    redirect_to :action => :index
  end

protected

  def build_cms_site
    @cms_site = Cms::Site.new(params[:cms_site])
    @cms_site.hostname ||= request.host.downcase
  end

  def load_cms_site
    @cms_site = Cms::Site.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Site not found'
    redirect_to :action => :index
  end

end

app/controllers/cms_admin/snippets_controller.rb
class CmsAdmin::SnippetsController < CmsAdmin::BaseController

  before_filter :build_cms_snippet, :only => [:new, :create]
  before_filter :load_cms_snippet,  :only => [:edit, :update, :destroy]

  def index
    return redirect_to :action => :new if @cms_site.snippets.count == 0
    @cms_snippets = @cms_site.snippets.all(:order => 'label')
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @cms_snippet.save!
    flash[:notice] = 'Snippet created'
    redirect_to :action => :edit, :id => @cms_snippet
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create snippet'
    render :action => :new
  end

  def update
    @cms_snippet.update_attributes!(params[:cms_snippet])
    flash[:notice] = 'Snippet updated'
    redirect_to :action => :edit, :id => @cms_snippet
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update snippet'
    render :action => :edit
  end

  def destroy
    @cms_snippet.destroy
    flash[:notice] = 'Snippet deleted'
    redirect_to :action => :index
  end

protected

  def build_cms_snippet
    @cms_snippet = @cms_site.snippets.new(params[:cms_snippet])
  end

  def load_cms_snippet
    @cms_snippet = @cms_site.snippets.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Snippet not found'
    redirect_to :action => :index
  end
end

app/controllers/cms_admin/uploads_controller.rb
class CmsAdmin::UploadsController < CmsAdmin::BaseController
  
  before_filter :load_cms_upload, :only => :destroy
  
  def index
    render
  end
  
  def create
    @cms_upload = @cms_site.uploads.create!(:file => params[:file])
    render :partial => 'file', :object => @cms_upload
  rescue ActiveRecord::RecordInvalid
    render :nothing => true, :status => :bad_request
  end
  
  def destroy
    @cms_upload.destroy
  end
  
protected
  
  def load_cms_upload
    @cms_upload = @cms_site.uploads.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :nothing => true
  end
end

app/views/cms_admin/pages/_form.html.erb
<% content_for :right_column do %>
  <div id='page_save' class='box'>
    <label>
      <input type='checkbox'/>
      Published
    </label>
    <button></button>
  </div>
  <%= render :partial => 'cms_admin/uploads/index' %>
<% end %>

<%= form.text_field :label, :id => (@cms_page.new_record?? 'slugify' : nil) %>

<div class='page_form_extras'>
  <% unless @cms_site.pages.count == 0 || @cms_site.pages.root == @cms_page%>
    <%= form.text_field :slug, :id => 'slug' %>
  <% end %>
  <% if (options = Cms::Layout.options_for_select(@cms_site)).present? %>
    <%= form.select :layout_id, options, {}, 'data-page-id' => @cms_page.id.to_i, :label => 'Layout' %>
  <% end %>
  <% if (options = Cms::Page.options_for_select(@cms_site, @cms_page)).present? %>
    <%= form.select :parent_id, options %>
  <% end %>
  <% if (options = Cms::Page.options_for_select(@cms_site, @cms_page, nil, 0, false)).present? %>
    <%= form.select :target_page_id, [['---- No Redirect ----', nil]] + options, :label => 'Redirect To Page' %>
  <% end %>
  <%= cms_hook :page_form, :object => form %>
</div>

<%= render :partial => 'form_blocks' %>

<%= form.simple_field nil, nil, :class => 'submit_element' do %>
  <%= form.check_box :is_published, :disable_builder => true %>
  <%= form.label_for :is_published, :label => 'Published' %>
  <%= form.submit 'Preview', :name => 'preview', :id => nil, :disable_builder => true %>
  <%= form.submit @cms_page.new_record? ? 'Create Page' : 'Update Page', :disable_builder => true %>
<% end %>

app/views/cms_admin/pages/_form_blocks.html.erb
<div id='form_blocks'>
  <%= fields_for :blocks, nil, :builder => ComfortableMexicanSofa::FormBuilder do |cms_blocks| %>
    <% @cms_page.tags(true).select{|t| t.is_cms_block?}.each do |tag| %>
      <%= cms_blocks.send(tag.class.to_s.demodulize.underscore, tag)%>
    <% end %>
  <% end %>
</div>

app/views/cms_admin/pages/_index_branch.html.erb
<% 
  cms_page    ||= index_branch 
  has_children  = cms_page.children.present?
  has_siblings  = cms_page.siblings.present?
  branch_open   = (session[:cms_page_tree] || []).member?(cms_page.id.to_s) || cms_page.root?
%>

<li id='<%= dom_id(cms_page) %>'>
  <div class='item'>
    <div class='toggle <%= 'open' if branch_open %>'>
      <%= 
        if has_children && !cms_page.root?
          link_to span_tag('toggle'), toggle_branch_cms_admin_page_path(cms_page), :remote => true
        end
      %>
    </div>
    <div class='icon'>
      <% if has_siblings %>
        <div class='dragger'><span>drag</span></div>
      <% end %>
    </div>
    <div class='action_links'>
      <%= link_to 'Add Child Page', new_cms_admin_page_path(:parent_id => cms_page.id) %>
      <%= link_to 'Edit', edit_cms_admin_page_path(cms_page) %>
      <%= link_to 'Delete', cms_admin_page_path(cms_page), :method => :delete, :confirm => 'Are you sure?' %>
    </div>
    <div class='label'>
      <%= link_to cms_page.label, edit_cms_admin_page_path(cms_page) %>
      <div class='sublabel'>
        <%= link_to cms_page.url, cms_page.full_path, :target => '_blank' %>
      </div>
    </div>
  </div>
  <% if has_children && branch_open %>
    <ul>
      <%= render :partial => 'index_branch', :collection => cms_page.children %>
    </ul>
  <% end %>
</li>

app/views/cms_admin/pages/edit.html.erb
<%= link_to span_tag(pluralize(@cms_page.revisions.count, 'revision')), cms_admin_page_revisions_path(@cms_page), :class => 'big button' %>
<h1> Editing Page </h1>

<%= cms_form_for @cms_page, :url => {:action => :update} do |form| %>
  <%= render :partial => 'form', :object => form %>
<% end %>

app/views/cms_admin/pages/form_blocks.js.erb
$('#form_blocks').replaceWith('<%= escape_javascript(render(:partial => "form_blocks")) %>');
$.CMS.enable_codemirror();

app/views/cms_admin/pages/index.html.erb
<%= link_to span_tag('Create New Page'), new_cms_admin_page_path, :class => 'big button' %>
<h1>Pages</h1>

<ul class='list sortable'>
  <%= render :partial => 'index_branch', :collection => @cms_pages %>
</ul>

app/views/cms_admin/pages/new.html.erb
<h1> New Page </h1>

<%= cms_form_for @cms_page, :url => {:action => :create} do |form| %>
  <%= render :partial => 'form', :object => form %>
<% end %>

app/views/cms_admin/pages/toggle_branch.js.erb
var li = $('li#cms_page_<%=@cms_page.id%>');
li.find('.item .toggle').first().toggleClass('open');

<% if session[:cms_page_tree].member?(@cms_page.id.to_s) %>
  if(!li.find('ul')[0]) {
    li.append('<ul><%= escape_javascript(render :partial => "index_branch", :collection => @cms_page.children) %></ul>');
    $.CMS.enable_sortable_list();
  }
<% else %>
  li.find('ul').remove();
<% end %>